name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Tests
    env:
      TESTING: true
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9' 
        
      - name: Set up a Python virtual environment
        run: python -m venv app/venv
     
      - name: Change Permissions
        run: |
            chmod +x app/venv/bin/python3
            chmod +x app/venv/bin/pip
      
      - name: Install Dependencies
        run: app/venv/bin/python3 -m pip install -r requirements.txt 

      - name: Run tests
        run: ./run_test.sh

